services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: reimbursement-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/data:/app/data
    environment:
      - PYTHONPATH=/app
    networks:
      - reimbursement-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reimbursement-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - reimbursement-network
    restart: unless-stopped

networks:
  reimbursement-network:
    driver: bridge

volumes:
  uploads:
  database: